### ISSUE TITLE
Non-ASCII characters in connection string password cause UnicodeEncodeError in cleanup

### ISSUE THREAD

**Issue by daybarr** [mkleehammer/pyodbc#54]
This script successfully connects to a SQL Server database using a login with a non-ASCII character in the password, but causes a `UnicodeEncodeError` when garbage collecting the pyodbc connection (I assume) and crashes python:

``` python
#!/usr/bin/env python
# encoding: utf-8
from __future__ import unicode_literals, print_function

import gc
import sys

import pyodbc

# Please ensure these are valid parameters for your test SQL Server - if pyodbc
# cannot establish a connection then the bug seems to be avoided.
CONN_PARTS = {
    'DRIVER': '{SQL Server}',
    'Server': '.\\SQLEXPRESS',
    'DATABASE': 'test_pyodbc',
    'UID': 'test_pyodbc_unicode',

    # PWD must contain Unicode that cannot be encoded as ASCII to invoke crash.
    'PWD': 'pa££word',
}
CONN_STR = ";".join(key + '=' + val for key, val in CONN_PARTS.items())

def main():
    print('python version:', sys.version)
    print('pyodbc version:', pyodbc.version)
    try:
        print("Connecting", CONN_STR)
        pyodbc.connect(CONN_STR)
        print("Connected OK")
    except Exception as err:
        print("Failed to connect - is your connection string correct?")
        print(err)
        exit(1)

    print('About to garbage collect')
    gc.collect()
    print('No crash - did you forget to use a Unicode PWD or fix the bug?')
    exit(1)

if __name__ == "__main__":
    main()
```

Output on my Windows 7 system, with the [latest 3.0.10 release from pypi](https://pypi.python.org/pypi/pyodbc/3.0.10) installed by pip from the wheel:

```
python version: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
pyodbc version: 3.0.10
Connecting PWD=pa££word;DATABASE=test_pyodbc;DRIVER={SQL Server};UID=test_pyodbc_unicode;Server=.\SQLEXPRESS
Connected OK
About to garbage collect
Exception UnicodeEncodeError: UnicodeEncodeError('ascii', u'PWD=pa\xa3\xa3word;DATABASE=test_pyodbc;DRIVER={SQL Server};UID=test_pyodbc_unicode;Server=.\\SQLEXPRESS', 6, 8, 'ordinal not in range(128)') in 'garbage collection' ignored
Fatal Python error: unexpected exception during garbage collection

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

If we remove the 4 lines of explicit `gc.collect` stuff at the end of `main` and replace with a dummy loop:

``` python
    for i in xrange(2):
        print("Fake work", i)
    print("Done")
```

Then python itself doesn't crash, but the `UnicodeEncodeError` is raised when the loop finishes, before we print `Done`:

```
python version: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
pyodbc version: 3.0.10
Connecting PWD=pa££word;DATABASE=test_pyodbc;DRIVER={SQL Server};UID=test_pyodbc_unicode;Server=.\SQLEXPRESS
Connected OK
Fake work 0
Fake work 1
Traceback (most recent call last):
  File "./pyodbc_crash.py", line 40, in <module>
    main()
  File "./pyodbc_crash.py", line 35, in main
    for i in xrange(2):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-7: ordinal not in range(128)
```

I can also reproduce with the latest code from master built with `python setup.py bdist_wininst`:

``````
python version: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
pyodbc version: 3.0.11b8
Connecting PWD=pa££word;DATABASE=test_pyodbc;DRIVER={SQL Server};UID=test_pyodbc_unicode;Server=.\SQLEXPRESS
Connected OK
Fake work 0
Fake work 1
Traceback (most recent call last):
  File "c:\Users\day.barr\bromium-management-server\bin\python-script.py", line 66, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "pyodbc_crash.py", line 40, in <module>
    main()
  File "pyodbc_crash.py", line 35, in main
    for i in xrange(2):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-7: ordinal not in range(128)```
``````

**Comment by mkleehammer** [comment]
I believe all Unicode issues are fixed by the 4.0 release.

**Comment by scarlatshay** [comment]
@mkleehammer I have just reproduced this using pyodbc 4.0.23.
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 35: ordinal not in range(128)`

Can you please have another look ? :)

**Comment by dbrennand** [comment]
Issue still persists, using Python 2.7: `UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 18: ordinal not in range(128)`
