### ISSUE TITLE
Type annotations for mypy

### ISSUE THREAD

**Issue by MartinThoma** [mkleehammer/pyodbc#831]
I've recently seen that pyodbc is one of the projects that doesn't come with type hints. It would be pretty awesome if one could add this.

I wanted to add them myself, but the protect seems to be almost purely C++. I have no clue how to properly annotate that. My hope was that we could add stub files (`.pyi`) for it. Does anybody have an idea how to do this? @mkleehammer Would you be open to add such stub files?

**Comment by mkleehammer** [comment]
I'm certainly open to it, but like you I haven't researched it yet.  I'll look into it after I get this bug list down and make sure it is stable.

**Comment by MartinThoma** [comment]
If you want general information about type annotations: https://medium.com/analytics-vidhya/type-annotations-in-python-3-8-3b401384403d

For libraries, there are 3 options:

* Full integration: I would consider that if you want to support Python 3.6+. If you want to support old Python versions, this will not work.
* Type comments: Directly in the code. IMHO it looks ugly, but serves as documentation as well.
* Type stubs: Extra files with type hints. You will only have the function signatures (replace the body by `...`) and store the file as `.pyi`. It does not have any effect on running Python, but still allows people/the editor to use the annotation.

**Comment by keitherskine** [comment]
Fixed by #864.

**Comment by jonaslb** [comment]
pyodbc is still not compatible with static checking with mypy / according to specifications due to issues https://github.com/python/mypy/issues/16987 / https://github.com/python/typing/issues/1333 . Essentially, there appears to be no proper way of annotating a top level single-file module. I have found no good workarounds besides a mypy override to ignore it.
